run:
  # Our CI expects a vendor directory, hence we have to use -mod=readonly here as well.
  modules-download-mode: readonly
  deadline: 30m
  timeout: 5m

# default linters are enabled `golangci-lint help linters`
linters:
  disable-all: true
  enable:
  - errcheck
  - gosec
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - typecheck
  - unused
