project_name: ocm-backplane

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
      - "GO111MODULE=on"
      - "GOFLAGS=-mod=readonly -trimpath"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      # The "-X" go flag sets the Version
      - -X github.com/openshift/backplane-cli/pkg/info.Version={{.Version}}
    main: ./cmd/ocm-backplane/
    binary: ocm-backplane

archives:
  - name_template: '{{ .ProjectName }}_{{- .Version }}_{{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end}}'

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: "openshift"
    name: "backplane-cli"
