// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/backplane-cli/pkg/ocm (interfaces: OCMInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	sdk "github.com/openshift-online/ocm-sdk-go"
	v1 "github.com/openshift-online/ocm-sdk-go/accesstransparency/v1"
	v10 "github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1"
)

// MockOCMInterface is a mock of OCMInterface interface.
type MockOCMInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOCMInterfaceMockRecorder
}

// MockOCMInterfaceMockRecorder is the mock recorder for MockOCMInterface.
type MockOCMInterfaceMockRecorder struct {
	mock *MockOCMInterface
}

// NewMockOCMInterface creates a new mock instance.
func NewMockOCMInterface(ctrl *gomock.Controller) *MockOCMInterface {
	mock := &MockOCMInterface{ctrl: ctrl}
	mock.recorder = &MockOCMInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOCMInterface) EXPECT() *MockOCMInterfaceMockRecorder {
	return m.recorder
}

// CreateAccessRequestDecision mocks base method.
func (m *MockOCMInterface) CreateAccessRequestDecision(arg0 *sdk.Connection, arg1 *v1.AccessRequest, arg2 v1.DecisionDecision, arg3 string) (*v1.Decision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessRequestDecision", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*v1.Decision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessRequestDecision indicates an expected call of CreateAccessRequestDecision.
func (mr *MockOCMInterfaceMockRecorder) CreateAccessRequestDecision(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessRequestDecision", reflect.TypeOf((*MockOCMInterface)(nil).CreateAccessRequestDecision), arg0, arg1, arg2, arg3)
}

// CreateClusterAccessRequest mocks base method.
func (m *MockOCMInterface) CreateClusterAccessRequest(arg0 *sdk.Connection, arg1, arg2, arg3, arg4 string) (*v1.AccessRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClusterAccessRequest", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*v1.AccessRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClusterAccessRequest indicates an expected call of CreateClusterAccessRequest.
func (mr *MockOCMInterfaceMockRecorder) CreateClusterAccessRequest(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClusterAccessRequest", reflect.TypeOf((*MockOCMInterface)(nil).CreateClusterAccessRequest), arg0, arg1, arg2, arg3, arg4)
}

// GetClusterActiveAccessRequest mocks base method.
func (m *MockOCMInterface) GetClusterActiveAccessRequest(arg0 *sdk.Connection, arg1 string) (*v1.AccessRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterActiveAccessRequest", arg0, arg1)
	ret0, _ := ret[0].(*v1.AccessRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterActiveAccessRequest indicates an expected call of GetClusterActiveAccessRequest.
func (mr *MockOCMInterfaceMockRecorder) GetClusterActiveAccessRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterActiveAccessRequest", reflect.TypeOf((*MockOCMInterface)(nil).GetClusterActiveAccessRequest), arg0, arg1)
}

// GetClusterInfoByID mocks base method.
func (m *MockOCMInterface) GetClusterInfoByID(arg0 string) (*v10.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterInfoByID", arg0)
	ret0, _ := ret[0].(*v10.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterInfoByID indicates an expected call of GetClusterInfoByID.
func (mr *MockOCMInterfaceMockRecorder) GetClusterInfoByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterInfoByID", reflect.TypeOf((*MockOCMInterface)(nil).GetClusterInfoByID), arg0)
}

// GetClusterInfoByIDWithConn mocks base method.
func (m *MockOCMInterface) GetClusterInfoByIDWithConn(arg0 *sdk.Connection, arg1 string) (*v10.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterInfoByIDWithConn", arg0, arg1)
	ret0, _ := ret[0].(*v10.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterInfoByIDWithConn indicates an expected call of GetClusterInfoByIDWithConn.
func (mr *MockOCMInterfaceMockRecorder) GetClusterInfoByIDWithConn(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterInfoByIDWithConn", reflect.TypeOf((*MockOCMInterface)(nil).GetClusterInfoByIDWithConn), arg0, arg1)
}

// GetManagingCluster mocks base method.
func (m *MockOCMInterface) GetManagingCluster(arg0 string) (string, string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManagingCluster", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetManagingCluster indicates an expected call of GetManagingCluster.
func (mr *MockOCMInterfaceMockRecorder) GetManagingCluster(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManagingCluster", reflect.TypeOf((*MockOCMInterface)(nil).GetManagingCluster), arg0)
}

// GetOCMAccessToken mocks base method.
func (m *MockOCMInterface) GetOCMAccessToken() (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOCMAccessToken")
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOCMAccessToken indicates an expected call of GetOCMAccessToken.
func (mr *MockOCMInterfaceMockRecorder) GetOCMAccessToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOCMAccessToken", reflect.TypeOf((*MockOCMInterface)(nil).GetOCMAccessToken))
}

// GetOCMAccessTokenWithConn mocks base method.
func (m *MockOCMInterface) GetOCMAccessTokenWithConn(arg0 *sdk.Connection) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOCMAccessTokenWithConn", arg0)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOCMAccessTokenWithConn indicates an expected call of GetOCMAccessTokenWithConn.
func (mr *MockOCMInterfaceMockRecorder) GetOCMAccessTokenWithConn(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOCMAccessTokenWithConn", reflect.TypeOf((*MockOCMInterface)(nil).GetOCMAccessTokenWithConn), arg0)
}

// GetOCMEnvironment mocks base method.
func (m *MockOCMInterface) GetOCMEnvironment() (*v10.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOCMEnvironment")
	ret0, _ := ret[0].(*v10.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOCMEnvironment indicates an expected call of GetOCMEnvironment.
func (mr *MockOCMInterfaceMockRecorder) GetOCMEnvironment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOCMEnvironment", reflect.TypeOf((*MockOCMInterface)(nil).GetOCMEnvironment))
}

// GetPullSecret mocks base method.
func (m *MockOCMInterface) GetPullSecret() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullSecret")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullSecret indicates an expected call of GetPullSecret.
func (mr *MockOCMInterfaceMockRecorder) GetPullSecret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullSecret", reflect.TypeOf((*MockOCMInterface)(nil).GetPullSecret))
}

// GetServiceCluster mocks base method.
func (m *MockOCMInterface) GetServiceCluster(arg0 string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceCluster", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetServiceCluster indicates an expected call of GetServiceCluster.
func (mr *MockOCMInterfaceMockRecorder) GetServiceCluster(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceCluster", reflect.TypeOf((*MockOCMInterface)(nil).GetServiceCluster), arg0)
}

// GetStsSupportJumpRoleARN mocks base method.
func (m *MockOCMInterface) GetStsSupportJumpRoleARN(arg0 *sdk.Connection, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStsSupportJumpRoleARN", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStsSupportJumpRoleARN indicates an expected call of GetStsSupportJumpRoleARN.
func (mr *MockOCMInterfaceMockRecorder) GetStsSupportJumpRoleARN(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStsSupportJumpRoleARN", reflect.TypeOf((*MockOCMInterface)(nil).GetStsSupportJumpRoleARN), arg0, arg1)
}

// GetTargetCluster mocks base method.
func (m *MockOCMInterface) GetTargetCluster(arg0 string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTargetCluster", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTargetCluster indicates an expected call of GetTargetCluster.
func (mr *MockOCMInterfaceMockRecorder) GetTargetCluster(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetCluster", reflect.TypeOf((*MockOCMInterface)(nil).GetTargetCluster), arg0)
}

// IsClusterAccessProtectionEnabled mocks base method.
func (m *MockOCMInterface) IsClusterAccessProtectionEnabled(arg0 *sdk.Connection, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsClusterAccessProtectionEnabled", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsClusterAccessProtectionEnabled indicates an expected call of IsClusterAccessProtectionEnabled.
func (mr *MockOCMInterfaceMockRecorder) IsClusterAccessProtectionEnabled(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsClusterAccessProtectionEnabled", reflect.TypeOf((*MockOCMInterface)(nil).IsClusterAccessProtectionEnabled), arg0, arg1)
}

// IsClusterHibernating mocks base method.
func (m *MockOCMInterface) IsClusterHibernating(arg0 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsClusterHibernating", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsClusterHibernating indicates an expected call of IsClusterHibernating.
func (mr *MockOCMInterfaceMockRecorder) IsClusterHibernating(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsClusterHibernating", reflect.TypeOf((*MockOCMInterface)(nil).IsClusterHibernating), arg0)
}

// IsProduction mocks base method.
func (m *MockOCMInterface) IsProduction() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProduction")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsProduction indicates an expected call of IsProduction.
func (mr *MockOCMInterfaceMockRecorder) IsProduction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProduction", reflect.TypeOf((*MockOCMInterface)(nil).IsProduction))
}

// SetupOCMConnection mocks base method.
func (m *MockOCMInterface) SetupOCMConnection() (*sdk.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupOCMConnection")
	ret0, _ := ret[0].(*sdk.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetupOCMConnection indicates an expected call of SetupOCMConnection.
func (mr *MockOCMInterfaceMockRecorder) SetupOCMConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupOCMConnection", reflect.TypeOf((*MockOCMInterface)(nil).SetupOCMConnection))
}
