// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/backplane-cli/pkg/ocm (interfaces: OCMInterface)
//
// Generated by this command:
//
//	mockgen -destination=./pkg/ocm/mocks/ocmWrapperMock.go -package=mocks github.com/openshift/backplane-cli/pkg/ocm OCMInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	v1 "github.com/openshift-online/ocm-api-model/clientapi/accesstransparency/v1"
	v10 "github.com/openshift-online/ocm-api-model/clientapi/clustersmgmt/v1"
	sdk "github.com/openshift-online/ocm-sdk-go"
	gomock "go.uber.org/mock/gomock"
)

// MockOCMInterface is a mock of OCMInterface interface.
type MockOCMInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOCMInterfaceMockRecorder
	isgomock struct{}
}

// MockOCMInterfaceMockRecorder is the mock recorder for MockOCMInterface.
type MockOCMInterfaceMockRecorder struct {
	mock *MockOCMInterface
}

// NewMockOCMInterface creates a new mock instance.
func NewMockOCMInterface(ctrl *gomock.Controller) *MockOCMInterface {
	mock := &MockOCMInterface{ctrl: ctrl}
	mock.recorder = &MockOCMInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOCMInterface) EXPECT() *MockOCMInterfaceMockRecorder {
	return m.recorder
}

// CreateAccessRequestDecision mocks base method.
func (m *MockOCMInterface) CreateAccessRequestDecision(ocmConnection *sdk.Connection, accessRequest *v1.AccessRequest, decision v1.DecisionDecision, justification string) (*v1.Decision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessRequestDecision", ocmConnection, accessRequest, decision, justification)
	ret0, _ := ret[0].(*v1.Decision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessRequestDecision indicates an expected call of CreateAccessRequestDecision.
func (mr *MockOCMInterfaceMockRecorder) CreateAccessRequestDecision(ocmConnection, accessRequest, decision, justification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessRequestDecision", reflect.TypeOf((*MockOCMInterface)(nil).CreateAccessRequestDecision), ocmConnection, accessRequest, decision, justification)
}

// CreateClusterAccessRequest mocks base method.
func (m *MockOCMInterface) CreateClusterAccessRequest(ocmConnection *sdk.Connection, clusterID, reason, jiraIssueID, approvalDuration string) (*v1.AccessRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClusterAccessRequest", ocmConnection, clusterID, reason, jiraIssueID, approvalDuration)
	ret0, _ := ret[0].(*v1.AccessRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClusterAccessRequest indicates an expected call of CreateClusterAccessRequest.
func (mr *MockOCMInterfaceMockRecorder) CreateClusterAccessRequest(ocmConnection, clusterID, reason, jiraIssueID, approvalDuration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClusterAccessRequest", reflect.TypeOf((*MockOCMInterface)(nil).CreateClusterAccessRequest), ocmConnection, clusterID, reason, jiraIssueID, approvalDuration)
}

// GetClusterActiveAccessRequest mocks base method.
func (m *MockOCMInterface) GetClusterActiveAccessRequest(ocmConnection *sdk.Connection, clusterID string) (*v1.AccessRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterActiveAccessRequest", ocmConnection, clusterID)
	ret0, _ := ret[0].(*v1.AccessRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterActiveAccessRequest indicates an expected call of GetClusterActiveAccessRequest.
func (mr *MockOCMInterfaceMockRecorder) GetClusterActiveAccessRequest(ocmConnection, clusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterActiveAccessRequest", reflect.TypeOf((*MockOCMInterface)(nil).GetClusterActiveAccessRequest), ocmConnection, clusterID)
}

// GetClusterInfoByID mocks base method.
func (m *MockOCMInterface) GetClusterInfoByID(clusterID string) (*v10.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterInfoByID", clusterID)
	ret0, _ := ret[0].(*v10.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterInfoByID indicates an expected call of GetClusterInfoByID.
func (mr *MockOCMInterfaceMockRecorder) GetClusterInfoByID(clusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterInfoByID", reflect.TypeOf((*MockOCMInterface)(nil).GetClusterInfoByID), clusterID)
}

// GetClusterInfoByIDWithConn mocks base method.
func (m *MockOCMInterface) GetClusterInfoByIDWithConn(ocmConnection *sdk.Connection, clusterID string) (*v10.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterInfoByIDWithConn", ocmConnection, clusterID)
	ret0, _ := ret[0].(*v10.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterInfoByIDWithConn indicates an expected call of GetClusterInfoByIDWithConn.
func (mr *MockOCMInterfaceMockRecorder) GetClusterInfoByIDWithConn(ocmConnection, clusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterInfoByIDWithConn", reflect.TypeOf((*MockOCMInterface)(nil).GetClusterInfoByIDWithConn), ocmConnection, clusterID)
}

// GetManagingCluster mocks base method.
func (m *MockOCMInterface) GetManagingCluster(clusterKey string) (string, string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManagingCluster", clusterKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetManagingCluster indicates an expected call of GetManagingCluster.
func (mr *MockOCMInterfaceMockRecorder) GetManagingCluster(clusterKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManagingCluster", reflect.TypeOf((*MockOCMInterface)(nil).GetManagingCluster), clusterKey)
}

// GetOCMAccessToken mocks base method.
func (m *MockOCMInterface) GetOCMAccessToken() (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOCMAccessToken")
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOCMAccessToken indicates an expected call of GetOCMAccessToken.
func (mr *MockOCMInterfaceMockRecorder) GetOCMAccessToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOCMAccessToken", reflect.TypeOf((*MockOCMInterface)(nil).GetOCMAccessToken))
}

// GetOCMAccessTokenWithConn mocks base method.
func (m *MockOCMInterface) GetOCMAccessTokenWithConn(ocmConnection *sdk.Connection) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOCMAccessTokenWithConn", ocmConnection)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOCMAccessTokenWithConn indicates an expected call of GetOCMAccessTokenWithConn.
func (mr *MockOCMInterfaceMockRecorder) GetOCMAccessTokenWithConn(ocmConnection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOCMAccessTokenWithConn", reflect.TypeOf((*MockOCMInterface)(nil).GetOCMAccessTokenWithConn), ocmConnection)
}

// GetOCMEnvironment mocks base method.
func (m *MockOCMInterface) GetOCMEnvironment() (*v10.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOCMEnvironment")
	ret0, _ := ret[0].(*v10.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOCMEnvironment indicates an expected call of GetOCMEnvironment.
func (mr *MockOCMInterfaceMockRecorder) GetOCMEnvironment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOCMEnvironment", reflect.TypeOf((*MockOCMInterface)(nil).GetOCMEnvironment))
}

// GetOCMEnvironmentWithConn mocks base method.
func (m *MockOCMInterface) GetOCMEnvironmentWithConn(connection *sdk.Connection) (*v10.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOCMEnvironmentWithConn", connection)
	ret0, _ := ret[0].(*v10.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOCMEnvironmentWithConn indicates an expected call of GetOCMEnvironmentWithConn.
func (mr *MockOCMInterfaceMockRecorder) GetOCMEnvironmentWithConn(connection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOCMEnvironmentWithConn", reflect.TypeOf((*MockOCMInterface)(nil).GetOCMEnvironmentWithConn), connection)
}

// GetPullSecret mocks base method.
func (m *MockOCMInterface) GetPullSecret() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullSecret")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullSecret indicates an expected call of GetPullSecret.
func (mr *MockOCMInterfaceMockRecorder) GetPullSecret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullSecret", reflect.TypeOf((*MockOCMInterface)(nil).GetPullSecret))
}

// GetServiceCluster mocks base method.
func (m *MockOCMInterface) GetServiceCluster(clusterKey string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceCluster", clusterKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetServiceCluster indicates an expected call of GetServiceCluster.
func (mr *MockOCMInterfaceMockRecorder) GetServiceCluster(clusterKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceCluster", reflect.TypeOf((*MockOCMInterface)(nil).GetServiceCluster), clusterKey)
}

// GetStsSupportJumpRoleARN mocks base method.
func (m *MockOCMInterface) GetStsSupportJumpRoleARN(ocmConnection *sdk.Connection, clusterID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStsSupportJumpRoleARN", ocmConnection, clusterID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStsSupportJumpRoleARN indicates an expected call of GetStsSupportJumpRoleARN.
func (mr *MockOCMInterfaceMockRecorder) GetStsSupportJumpRoleARN(ocmConnection, clusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStsSupportJumpRoleARN", reflect.TypeOf((*MockOCMInterface)(nil).GetStsSupportJumpRoleARN), ocmConnection, clusterID)
}

// GetTargetCluster mocks base method.
func (m *MockOCMInterface) GetTargetCluster(clusterKey string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTargetCluster", clusterKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTargetCluster indicates an expected call of GetTargetCluster.
func (mr *MockOCMInterfaceMockRecorder) GetTargetCluster(clusterKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetCluster", reflect.TypeOf((*MockOCMInterface)(nil).GetTargetCluster), clusterKey)
}

// GetTrustedIPList mocks base method.
func (m *MockOCMInterface) GetTrustedIPList(arg0 *sdk.Connection) (*v10.TrustedIpList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrustedIPList", arg0)
	ret0, _ := ret[0].(*v10.TrustedIpList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrustedIPList indicates an expected call of GetTrustedIPList.
func (mr *MockOCMInterfaceMockRecorder) GetTrustedIPList(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrustedIPList", reflect.TypeOf((*MockOCMInterface)(nil).GetTrustedIPList), arg0)
}

// IsClusterAccessProtectionEnabled mocks base method.
func (m *MockOCMInterface) IsClusterAccessProtectionEnabled(ocmConnection *sdk.Connection, clusterID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsClusterAccessProtectionEnabled", ocmConnection, clusterID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsClusterAccessProtectionEnabled indicates an expected call of IsClusterAccessProtectionEnabled.
func (mr *MockOCMInterfaceMockRecorder) IsClusterAccessProtectionEnabled(ocmConnection, clusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsClusterAccessProtectionEnabled", reflect.TypeOf((*MockOCMInterface)(nil).IsClusterAccessProtectionEnabled), ocmConnection, clusterID)
}

// IsClusterHibernating mocks base method.
func (m *MockOCMInterface) IsClusterHibernating(clusterID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsClusterHibernating", clusterID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsClusterHibernating indicates an expected call of IsClusterHibernating.
func (mr *MockOCMInterfaceMockRecorder) IsClusterHibernating(clusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsClusterHibernating", reflect.TypeOf((*MockOCMInterface)(nil).IsClusterHibernating), clusterID)
}

// IsProduction mocks base method.
func (m *MockOCMInterface) IsProduction() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProduction")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsProduction indicates an expected call of IsProduction.
func (mr *MockOCMInterfaceMockRecorder) IsProduction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProduction", reflect.TypeOf((*MockOCMInterface)(nil).IsProduction))
}

// SetupOCMConnection mocks base method.
func (m *MockOCMInterface) SetupOCMConnection() (*sdk.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupOCMConnection")
	ret0, _ := ret[0].(*sdk.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetupOCMConnection indicates an expected call of SetupOCMConnection.
func (mr *MockOCMInterfaceMockRecorder) SetupOCMConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupOCMConnection", reflect.TypeOf((*MockOCMInterface)(nil).SetupOCMConnection))
}
