// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/backplane-cli/pkg/utils (interfaces: ClientUtils)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	Openapi "github.com/openshift/backplane-api/pkg/client"
)

// MockClientUtils is a mock of ClientUtils interface.
type MockClientUtils struct {
	ctrl     *gomock.Controller
	recorder *MockClientUtilsMockRecorder
}

// MockClientUtilsMockRecorder is the mock recorder for MockClientUtils.
type MockClientUtilsMockRecorder struct {
	mock *MockClientUtils
}

// NewMockClientUtils creates a new mock instance.
func NewMockClientUtils(ctrl *gomock.Controller) *MockClientUtils {
	mock := &MockClientUtils{ctrl: ctrl}
	mock.recorder = &MockClientUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientUtils) EXPECT() *MockClientUtilsMockRecorder {
	return m.recorder
}

// GetBackplaneClient mocks base method.
func (m *MockClientUtils) GetBackplaneClient(arg0 string, arg1 *string) (Openapi.ClientInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackplaneClient", arg0, arg1)
	ret0, _ := ret[0].(Openapi.ClientInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackplaneClient indicates an expected call of GetBackplaneClient.
func (mr *MockClientUtilsMockRecorder) GetBackplaneClient(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackplaneClient", reflect.TypeOf((*MockClientUtils)(nil).GetBackplaneClient), arg0, arg1)
}

// MakeBackplaneAPIClient mocks base method.
func (m *MockClientUtils) MakeBackplaneAPIClient(arg0 string) (Openapi.ClientWithResponsesInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeBackplaneAPIClient", arg0)
	ret0, _ := ret[0].(Openapi.ClientWithResponsesInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeBackplaneAPIClient indicates an expected call of MakeBackplaneAPIClient.
func (mr *MockClientUtilsMockRecorder) MakeBackplaneAPIClient(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeBackplaneAPIClient", reflect.TypeOf((*MockClientUtils)(nil).MakeBackplaneAPIClient), arg0)
}

// MakeBackplaneAPIClientWithAccessToken mocks base method.
func (m *MockClientUtils) MakeBackplaneAPIClientWithAccessToken(arg0, arg1 string) (Openapi.ClientWithResponsesInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeBackplaneAPIClientWithAccessToken", arg0, arg1)
	ret0, _ := ret[0].(Openapi.ClientWithResponsesInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeBackplaneAPIClientWithAccessToken indicates an expected call of MakeBackplaneAPIClientWithAccessToken.
func (mr *MockClientUtilsMockRecorder) MakeBackplaneAPIClientWithAccessToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeBackplaneAPIClientWithAccessToken", reflect.TypeOf((*MockClientUtils)(nil).MakeBackplaneAPIClientWithAccessToken), arg0, arg1)
}

// MakeRawBackplaneAPIClient mocks base method.
func (m *MockClientUtils) MakeRawBackplaneAPIClient(arg0 string) (Openapi.ClientInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeRawBackplaneAPIClient", arg0)
	ret0, _ := ret[0].(Openapi.ClientInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeRawBackplaneAPIClient indicates an expected call of MakeRawBackplaneAPIClient.
func (mr *MockClientUtilsMockRecorder) MakeRawBackplaneAPIClient(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeRawBackplaneAPIClient", reflect.TypeOf((*MockClientUtils)(nil).MakeRawBackplaneAPIClient), arg0)
}

// MakeRawBackplaneAPIClientWithAccessToken mocks base method.
func (m *MockClientUtils) MakeRawBackplaneAPIClientWithAccessToken(arg0, arg1 string) (Openapi.ClientInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeRawBackplaneAPIClientWithAccessToken", arg0, arg1)
	ret0, _ := ret[0].(Openapi.ClientInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeRawBackplaneAPIClientWithAccessToken indicates an expected call of MakeRawBackplaneAPIClientWithAccessToken.
func (mr *MockClientUtilsMockRecorder) MakeRawBackplaneAPIClientWithAccessToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeRawBackplaneAPIClientWithAccessToken", reflect.TypeOf((*MockClientUtils)(nil).MakeRawBackplaneAPIClientWithAccessToken), arg0, arg1)
}

// SetClientProxyURL mocks base method.
func (m *MockClientUtils) SetClientProxyURL(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetClientProxyURL", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetClientProxyURL indicates an expected call of SetClientProxyURL.
func (mr *MockClientUtilsMockRecorder) SetClientProxyURL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetClientProxyURL", reflect.TypeOf((*MockClientUtils)(nil).SetClientProxyURL), arg0)
}
