// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/backplane-cli/pkg/utils (interfaces: ShellCheckerInterface)
//
// Generated by this command:
//
//	mockgen -destination=./pkg/utils/mocks/shellCheckerMock.go -package=mocks github.com/openshift/backplane-cli/pkg/utils ShellCheckerInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShellCheckerInterface is a mock of ShellCheckerInterface interface.
type MockShellCheckerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockShellCheckerInterfaceMockRecorder
	isgomock struct{}
}

// MockShellCheckerInterfaceMockRecorder is the mock recorder for MockShellCheckerInterface.
type MockShellCheckerInterfaceMockRecorder struct {
	mock *MockShellCheckerInterface
}

// NewMockShellCheckerInterface creates a new mock instance.
func NewMockShellCheckerInterface(ctrl *gomock.Controller) *MockShellCheckerInterface {
	mock := &MockShellCheckerInterface{ctrl: ctrl}
	mock.recorder = &MockShellCheckerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShellCheckerInterface) EXPECT() *MockShellCheckerInterfaceMockRecorder {
	return m.recorder
}

// IsValidShell mocks base method.
func (m *MockShellCheckerInterface) IsValidShell(shellPath string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidShell", shellPath)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsValidShell indicates an expected call of IsValidShell.
func (mr *MockShellCheckerInterfaceMockRecorder) IsValidShell(shellPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidShell", reflect.TypeOf((*MockShellCheckerInterface)(nil).IsValidShell), shellPath)
}
