// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/backplane-cli/pkg/cli/config (interfaces: ConfigAPIClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_config_api_client.go -package=mocks github.com/openshift/backplane-cli/pkg/cli/config ConfigAPIClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	Openapi "github.com/openshift/backplane-api/pkg/client"
	config "github.com/openshift/backplane-cli/pkg/cli/config"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigAPIClient is a mock of ConfigAPIClient interface.
type MockConfigAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockConfigAPIClientMockRecorder
	isgomock struct{}
}

// MockConfigAPIClientMockRecorder is the mock recorder for MockConfigAPIClient.
type MockConfigAPIClientMockRecorder struct {
	mock *MockConfigAPIClient
}

// NewMockConfigAPIClient creates a new mock instance.
func NewMockConfigAPIClient(ctrl *gomock.Controller) *MockConfigAPIClient {
	mock := &MockConfigAPIClient{ctrl: ctrl}
	mock.recorder = &MockConfigAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigAPIClient) EXPECT() *MockConfigAPIClientMockRecorder {
	return m.recorder
}

// FetchRemoteConfig mocks base method.
func (m *MockConfigAPIClient) FetchRemoteConfig(client Openapi.ClientInterface) (*config.RemoteConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRemoteConfig", client)
	ret0, _ := ret[0].(*config.RemoteConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRemoteConfig indicates an expected call of FetchRemoteConfig.
func (mr *MockConfigAPIClientMockRecorder) FetchRemoteConfig(client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRemoteConfig", reflect.TypeOf((*MockConfigAPIClient)(nil).FetchRemoteConfig), client)
}
