// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/backplane-cli/pkg/container (interfaces: ContainerEngine)
//
// Generated by this command:
//
//	mockgen -destination=./pkg/container/mocks/containerEngineMock.go -package=mocks github.com/openshift/backplane-cli/pkg/container ContainerEngine
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	container "github.com/openshift/backplane-cli/pkg/container"
	gomock "go.uber.org/mock/gomock"
)

// MockContainerEngine is a mock of ContainerEngine interface.
type MockContainerEngine struct {
	ctrl     *gomock.Controller
	recorder *MockContainerEngineMockRecorder
	isgomock struct{}
}

// MockContainerEngineMockRecorder is the mock recorder for MockContainerEngine.
type MockContainerEngineMockRecorder struct {
	mock *MockContainerEngine
}

// NewMockContainerEngine creates a new mock instance.
func NewMockContainerEngine(ctrl *gomock.Controller) *MockContainerEngine {
	mock := &MockContainerEngine{ctrl: ctrl}
	mock.recorder = &MockContainerEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainerEngine) EXPECT() *MockContainerEngineMockRecorder {
	return m.recorder
}

// ContainerIsExist mocks base method.
func (m *MockContainerEngine) ContainerIsExist(containerName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerIsExist", containerName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerIsExist indicates an expected call of ContainerIsExist.
func (mr *MockContainerEngineMockRecorder) ContainerIsExist(containerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerIsExist", reflect.TypeOf((*MockContainerEngine)(nil).ContainerIsExist), containerName)
}

// PullImage mocks base method.
func (m *MockContainerEngine) PullImage(imageName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullImage", imageName)
	ret0, _ := ret[0].(error)
	return ret0
}

// PullImage indicates an expected call of PullImage.
func (mr *MockContainerEngineMockRecorder) PullImage(imageName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullImage", reflect.TypeOf((*MockContainerEngine)(nil).PullImage), imageName)
}

// PutFileToMount mocks base method.
func (m *MockContainerEngine) PutFileToMount(filename string, content []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutFileToMount", filename, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutFileToMount indicates an expected call of PutFileToMount.
func (mr *MockContainerEngineMockRecorder) PutFileToMount(filename, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutFileToMount", reflect.TypeOf((*MockContainerEngine)(nil).PutFileToMount), filename, content)
}

// RunConsoleContainer mocks base method.
func (m *MockContainerEngine) RunConsoleContainer(containerName, port string, consoleArgs []string, envVars []container.EnvVar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunConsoleContainer", containerName, port, consoleArgs, envVars)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunConsoleContainer indicates an expected call of RunConsoleContainer.
func (mr *MockContainerEngineMockRecorder) RunConsoleContainer(containerName, port, consoleArgs, envVars any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunConsoleContainer", reflect.TypeOf((*MockContainerEngine)(nil).RunConsoleContainer), containerName, port, consoleArgs, envVars)
}

// RunMonitorPlugin mocks base method.
func (m *MockContainerEngine) RunMonitorPlugin(containerName, consoleContainerName, nginxConf string, pluginArgs []string, envVars []container.EnvVar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunMonitorPlugin", containerName, consoleContainerName, nginxConf, pluginArgs, envVars)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunMonitorPlugin indicates an expected call of RunMonitorPlugin.
func (mr *MockContainerEngineMockRecorder) RunMonitorPlugin(containerName, consoleContainerName, nginxConf, pluginArgs, envVars any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunMonitorPlugin", reflect.TypeOf((*MockContainerEngine)(nil).RunMonitorPlugin), containerName, consoleContainerName, nginxConf, pluginArgs, envVars)
}

// StopContainer mocks base method.
func (m *MockContainerEngine) StopContainer(containerName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopContainer", containerName)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopContainer indicates an expected call of StopContainer.
func (mr *MockContainerEngineMockRecorder) StopContainer(containerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopContainer", reflect.TypeOf((*MockContainerEngine)(nil).StopContainer), containerName)
}
