// Package BackplaneApi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.10.1 DO NOT EDIT.
package BackplaneApi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for JobStatusStatus.
const (
	JobStatusStatusFailed JobStatusStatus = "Failed"

	JobStatusStatusKilled JobStatusStatus = "Killed"

	JobStatusStatusPending JobStatusStatus = "Pending"

	JobStatusStatusRunning JobStatusStatus = "Running"

	JobStatusStatusSucceeded JobStatusStatus = "Succeeded"

	JobStatusStatusUnknown JobStatusStatus = "Unknown"
)

// Defines values for ScriptLanguage.
const (
	ScriptLanguageBash ScriptLanguage = "bash"

	ScriptLanguagePython ScriptLanguage = "python"
)

// Defines values for ScriptMetadataLanguage.
const (
	ScriptMetadataLanguageBash ScriptMetadataLanguage = "bash"

	ScriptMetadataLanguagePython ScriptMetadataLanguage = "python"
)

// Defines values for TestJobResultStatus.
const (
	TestJobResultStatusFailed TestJobResultStatus = "Failed"

	TestJobResultStatusPending TestJobResultStatus = "Pending"

	TestJobResultStatusRunning TestJobResultStatus = "Running"

	TestJobResultStatusSucceeded TestJobResultStatus = "Succeeded"
)

// Response for cloud handler
type CloudCredentialsResponse struct {
	// ClusterID
	ClusterID string `json:"clusterID"`

	// Link to the console, optional
	ConsoleLink *string `json:"consoleLink,omitempty"`

	// Cloud credentials, optional
	Credentials *string `json:"credentials,omitempty"`

	// Region, optional
	Region *string `json:"region,omitempty"`
}

// CreateJob defines model for CreateJob.
type CreateJob struct {
	// Name of the script to run
	CanonicalName *string `json:"canonicalName,omitempty"`

	// A map of parameters for the script, must be a flat object and matches
	// the parameters declared on the metadata
	Parameters *CreateJob_Parameters `json:"parameters,omitempty"`
}

// A map of parameters for the script, must be a flat object and matches
// the parameters declared on the metadata
type CreateJob_Parameters struct {
	AdditionalProperties map[string]string `json:"-"`
}

// Body for creating a test job
type CreateTestJob struct {
	// Flag to indicate whether to generate a template or execute the script
	DryRun *bool `json:"dryRun,omitempty"`

	// A map of parameters for the script, must be a flat object and matches
	// the parameters declared on the metadata
	Parameters *CreateTestJob_Parameters `json:"parameters,omitempty"`

	// Base64 encoded script body to run
	ScriptBody string `json:"scriptBody"`

	// Script metadata
	ScriptMetadata ScriptMetadata `json:"scriptMetadata"`
}

// A map of parameters for the script, must be a flat object and matches
// the parameters declared on the metadata
type CreateTestJob_Parameters struct {
	AdditionalProperties map[string]string `json:"-"`
}

// EnvDecl defines model for EnvDecl.
type EnvDecl struct {
	// A description of the env var
	Description *string `json:"description,omitempty"`

	// Key of the env
	Key *string `json:"key,omitempty"`

	// Whether this env var is optional
	Optional *bool `json:"optional,omitempty"`
}

// EnvRealised defines model for EnvRealised.
type EnvRealised struct {
	// Key of the env
	Key *string `json:"key,omitempty"`

	// The processed value of the env var
	Value *string `json:"value,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Error Message
	Message *string `json:"message,omitempty"`

	// HTTP status code
	StatusCode *int `json:"statusCode,omitempty"`
}

// Job defines model for Job.
type Job struct {
	// An unique id to identify this job run
	JobId     *string    `json:"jobId,omitempty"`
	JobStatus *JobStatus `json:"jobStatus,omitempty"`

	// A helpful message to the user
	Message *string `json:"message,omitempty"`

	// MD5 of the user who created the job
	UserMD5 *string `json:"userMD5,omitempty"`
}

// JobStatus defines model for JobStatus.
type JobStatus struct {
	// End/Finish time of the script
	End *time.Time `json:"end"`

	// A array of environment parameters for the script
	Envs *[]EnvRealised `json:"envs,omitempty"`

	// Namespace of the script being ran
	Namespace *string `json:"namespace,omitempty"`
	Script    *Script `json:"script,omitempty"`

	// Start time of the script
	Start *time.Time `json:"start,omitempty"`

	// status of the script
	Status *JobStatusStatus `json:"status,omitempty"`
}

// status of the script
type JobStatusStatus string

// LabelDecl defines model for LabelDecl.
type LabelDecl struct {
	// A brief description of the label
	Description *string `json:"description,omitempty"`

	// Key of the label
	Key *string `json:"key,omitempty"`

	// Values for the label
	Values *[]interface{} `json:"values,omitempty"`
}

// Login status response
type LoginResponse struct {
	// message
	Message *string `json:"message,omitempty"`

	// KubeAPI proxy URI
	ProxyUri *string `json:"proxy_uri,omitempty"`

	// status code
	StatusCode *int `json:"statusCode,omitempty"`
}

// Logs defines model for Logs.
type Logs struct {
	// Logs of the pod
	Logs *string `json:"logs,omitempty"`
}

// PolicyRule defines model for PolicyRule.
type PolicyRule struct {
	ApiGroups       *[]string `json:"apiGroups,omitempty" yaml:"apiGroups,omitempty"`
	NonResourceURLs *[]string `json:"nonResourceURLs,omitempty" yaml:"nonResourceURLs,omitempty"`
	ResourceNames   *[]string `json:"resourceNames,omitempty" yaml:"resourceNames,omitempty"`
	Resources       *[]string `json:"resources,omitempty" yaml:"resources,omitempty"`
	Verbs           *[]string `json:"verbs,omitempty" yaml:"verbs,omitempty"`
}

// RBAC declaration
type RBAC struct {
	ClusterRoleRules *[]PolicyRule   `json:"clusterRoleRules,omitempty" yaml:"clusterRoleRules,omitempty"`
	Roles            *[]RoleRbacDecl `json:"roles,omitempty" yaml:"roles,omitempty"`
}

// RoleRbacDecl defines model for RoleRbacDecl.
type RoleRbacDecl struct {
	Namespace *string       `json:"namespace,omitempty"`
	Rules     *[]PolicyRule `json:"rules,omitempty"`
}

// Script defines model for Script.
type Script struct {
	// Which groups are allowed to run this script
	AllowedGroups *[]string `json:"allowedGroups,omitempty"`

	// Author of the script, github username
	Author *string `json:"author,omitempty"`

	// Fully qualified name of the script, in the format of roleId/scriptname.
	// Must be unique, MR in-place check to enforce this
	CanonicalName *string `json:"canonicalName,omitempty"`

	// A brief description of the script and what it does
	Description *string `json:"description,omitempty"`

	// An array of environment variables for the script
	Envs *[]EnvDecl `json:"envs,omitempty"`

	// An array of labels for the script
	Labels *[]interface{} `json:"labels,omitempty"`

	// The script language
	Language *ScriptLanguage `json:"language,omitempty"`

	// Path from the repo root to the script
	Path *string `json:"path,omitempty"`

	// Permalink to the script file on git
	Permalink *string `json:"permalink,omitempty"`

	// RBAC declaration
	Rbac *RBAC `json:"rbac,omitempty" yaml:"rbac,omitempty"`

	// A shorter description for tables and lists
	ShortDescription *string `json:"shortDescription,omitempty"`
}

// The script language
type ScriptLanguage string

// Script metadata
type ScriptMetadata struct {
	AllowedGroups []string               `json:"allowedGroups"`
	Author        string                 `json:"author"`
	Description   string                 `json:"description"`
	Envs          []EnvDecl              `json:"envs"`
	File          string                 `json:"file"`
	Labels        []LabelDecl            `json:"labels"`
	Language      ScriptMetadataLanguage `json:"language"`
	Name          string                 `json:"name"`

	// RBAC declaration
	Rbac             RBAC   `json:"rbac" yaml:"rbac,omitempty"`
	ShortDescription string `json:"shortDescription"`
}

// ScriptMetadataLanguage defines model for ScriptMetadata.Language.
type ScriptMetadataLanguage string

// Scripts defines model for Scripts.
type Scripts []Script

// Body of response for a test job run
type TestJobResult struct {
	Message *string `json:"message,omitempty"`

	// Test run status
	Status *TestJobResultStatus `json:"status,omitempty"`

	// A unique id for test script run
	TestId string `json:"testId"`
}

// Test run status
type TestJobResultStatus string

// GetScriptsParams defines parameters for GetScripts.
type GetScriptsParams struct {
	Scriptname *string `json:"scriptname,omitempty"`
}

// CreateJobJSONBody defines parameters for CreateJob.
type CreateJobJSONBody CreateJob

// GetJobLogsParams defines parameters for GetJobLogs.
type GetJobLogsParams struct {
	// The version to return. Default is JSON, v2 is streaming
	Version *string `json:"version,omitempty"`

	// Specify if the logs should be followed.
	Follow *bool `json:"follow,omitempty"`
}

// CreateTestScriptRunJSONBody defines parameters for CreateTestScriptRun.
type CreateTestScriptRunJSONBody CreateTestJob

// GetTestScriptRunLogsParams defines parameters for GetTestScriptRunLogs.
type GetTestScriptRunLogsParams struct {
	// The version to return. Default is JSON, v2 is streaming
	Version *string `json:"version,omitempty"`

	// Specify if the logs should be followed.
	Follow *bool `json:"follow,omitempty"`
}

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody CreateJobJSONBody

// CreateTestScriptRunJSONRequestBody defines body for CreateTestScriptRun for application/json ContentType.
type CreateTestScriptRunJSONRequestBody CreateTestScriptRunJSONBody

// Getter for additional properties for CreateJob_Parameters. Returns the specified
// element and whether it was found
func (a CreateJob_Parameters) Get(fieldName string) (value string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CreateJob_Parameters
func (a *CreateJob_Parameters) Set(fieldName string, value string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CreateJob_Parameters to handle AdditionalProperties
func (a *CreateJob_Parameters) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CreateJob_Parameters to handle AdditionalProperties
func (a CreateJob_Parameters) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for CreateTestJob_Parameters. Returns the specified
// element and whether it was found
func (a CreateTestJob_Parameters) Get(fieldName string) (value string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CreateTestJob_Parameters
func (a *CreateTestJob_Parameters) Set(fieldName string, value string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CreateTestJob_Parameters to handle AdditionalProperties
func (a *CreateTestJob_Parameters) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CreateTestJob_Parameters to handle AdditionalProperties
func (a CreateTestJob_Parameters) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetCloudConsole request
	GetCloudConsole(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCloudCredentials request
	GetCloudCredentials(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteBackplaneClusterClusterId request
	DeleteBackplaneClusterClusterId(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetBackplaneClusterClusterId request
	GetBackplaneClusterClusterId(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HeadBackplaneClusterClusterId request
	HeadBackplaneClusterClusterId(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OptionsBackplaneClusterClusterId request
	OptionsBackplaneClusterClusterId(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchBackplaneClusterClusterId request
	PatchBackplaneClusterClusterId(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostBackplaneClusterClusterId request
	PostBackplaneClusterClusterId(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutBackplaneClusterClusterId request
	PutBackplaneClusterClusterId(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TraceBackplaneClusterClusterId request
	TraceBackplaneClusterClusterId(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LoginCluster request
	LoginCluster(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetScripts request
	GetScripts(ctx context.Context, params *GetScriptsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAllJobs request
	GetAllJobs(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateJob request with any body
	CreateJobWithBody(ctx context.Context, clusterId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateJob(ctx context.Context, clusterId string, body CreateJobJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteJob request
	DeleteJob(ctx context.Context, clusterId string, jobId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRun request
	GetRun(ctx context.Context, clusterId string, jobId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetJobLogs request
	GetJobLogs(ctx context.Context, clusterId string, jobId string, params *GetJobLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateTestScriptRun request with any body
	CreateTestScriptRunWithBody(ctx context.Context, clusterId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateTestScriptRun(ctx context.Context, clusterId string, body CreateTestScriptRunJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTestScriptRun request
	GetTestScriptRun(ctx context.Context, clusterId string, testId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTestScriptRunLogs request
	GetTestScriptRunLogs(ctx context.Context, clusterId string, testId string, params *GetTestScriptRunLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetCloudConsole(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCloudConsoleRequest(c.Server, clusterId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCloudCredentials(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCloudCredentialsRequest(c.Server, clusterId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteBackplaneClusterClusterId(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteBackplaneClusterClusterIdRequest(c.Server, clusterId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetBackplaneClusterClusterId(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBackplaneClusterClusterIdRequest(c.Server, clusterId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HeadBackplaneClusterClusterId(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHeadBackplaneClusterClusterIdRequest(c.Server, clusterId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OptionsBackplaneClusterClusterId(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOptionsBackplaneClusterClusterIdRequest(c.Server, clusterId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchBackplaneClusterClusterId(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchBackplaneClusterClusterIdRequest(c.Server, clusterId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostBackplaneClusterClusterId(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostBackplaneClusterClusterIdRequest(c.Server, clusterId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutBackplaneClusterClusterId(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutBackplaneClusterClusterIdRequest(c.Server, clusterId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TraceBackplaneClusterClusterId(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTraceBackplaneClusterClusterIdRequest(c.Server, clusterId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LoginCluster(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLoginClusterRequest(c.Server, clusterId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetScripts(ctx context.Context, params *GetScriptsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetScriptsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAllJobs(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAllJobsRequest(c.Server, clusterId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateJobWithBody(ctx context.Context, clusterId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateJobRequestWithBody(c.Server, clusterId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateJob(ctx context.Context, clusterId string, body CreateJobJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateJobRequest(c.Server, clusterId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteJob(ctx context.Context, clusterId string, jobId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteJobRequest(c.Server, clusterId, jobId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRun(ctx context.Context, clusterId string, jobId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRunRequest(c.Server, clusterId, jobId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetJobLogs(ctx context.Context, clusterId string, jobId string, params *GetJobLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetJobLogsRequest(c.Server, clusterId, jobId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateTestScriptRunWithBody(ctx context.Context, clusterId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateTestScriptRunRequestWithBody(c.Server, clusterId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateTestScriptRun(ctx context.Context, clusterId string, body CreateTestScriptRunJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateTestScriptRunRequest(c.Server, clusterId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTestScriptRun(ctx context.Context, clusterId string, testId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTestScriptRunRequest(c.Server, clusterId, testId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTestScriptRunLogs(ctx context.Context, clusterId string, testId string, params *GetTestScriptRunLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTestScriptRunLogsRequest(c.Server, clusterId, testId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCloudConsoleRequest generates requests for GetCloudConsole
func NewGetCloudConsoleRequest(server string, clusterId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backplane/cloud/console/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCloudCredentialsRequest generates requests for GetCloudCredentials
func NewGetCloudCredentialsRequest(server string, clusterId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backplane/cloud/credentials/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteBackplaneClusterClusterIdRequest generates requests for DeleteBackplaneClusterClusterId
func NewDeleteBackplaneClusterClusterIdRequest(server string, clusterId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backplane/cluster/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetBackplaneClusterClusterIdRequest generates requests for GetBackplaneClusterClusterId
func NewGetBackplaneClusterClusterIdRequest(server string, clusterId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backplane/cluster/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewHeadBackplaneClusterClusterIdRequest generates requests for HeadBackplaneClusterClusterId
func NewHeadBackplaneClusterClusterIdRequest(server string, clusterId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backplane/cluster/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("HEAD", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewOptionsBackplaneClusterClusterIdRequest generates requests for OptionsBackplaneClusterClusterId
func NewOptionsBackplaneClusterClusterIdRequest(server string, clusterId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backplane/cluster/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("OPTIONS", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchBackplaneClusterClusterIdRequest generates requests for PatchBackplaneClusterClusterId
func NewPatchBackplaneClusterClusterIdRequest(server string, clusterId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backplane/cluster/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostBackplaneClusterClusterIdRequest generates requests for PostBackplaneClusterClusterId
func NewPostBackplaneClusterClusterIdRequest(server string, clusterId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backplane/cluster/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutBackplaneClusterClusterIdRequest generates requests for PutBackplaneClusterClusterId
func NewPutBackplaneClusterClusterIdRequest(server string, clusterId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backplane/cluster/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTraceBackplaneClusterClusterIdRequest generates requests for TraceBackplaneClusterClusterId
func NewTraceBackplaneClusterClusterIdRequest(server string, clusterId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backplane/cluster/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("TRACE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewLoginClusterRequest generates requests for LoginCluster
func NewLoginClusterRequest(server string, clusterId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backplane/login/%s/", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetScriptsRequest generates requests for GetScripts
func NewGetScriptsRequest(server string, params *GetScriptsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backplane/script")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	queryValues := queryURL.Query()

	if params.Scriptname != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "scriptname", runtime.ParamLocationQuery, *params.Scriptname); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	queryURL.RawQuery = queryValues.Encode()

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAllJobsRequest generates requests for GetAllJobs
func NewGetAllJobsRequest(server string, clusterId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backplane/script/%s/job", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateJobRequest calls the generic CreateJob builder with application/json body
func NewCreateJobRequest(server string, clusterId string, body CreateJobJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateJobRequestWithBody(server, clusterId, "application/json", bodyReader)
}

// NewCreateJobRequestWithBody generates requests for CreateJob with any type of body
func NewCreateJobRequestWithBody(server string, clusterId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backplane/script/%s/job", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteJobRequest generates requests for DeleteJob
func NewDeleteJobRequest(server string, clusterId string, jobId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "jobId", runtime.ParamLocationPath, jobId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backplane/script/%s/job/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetRunRequest generates requests for GetRun
func NewGetRunRequest(server string, clusterId string, jobId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "jobId", runtime.ParamLocationPath, jobId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backplane/script/%s/job/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetJobLogsRequest generates requests for GetJobLogs
func NewGetJobLogsRequest(server string, clusterId string, jobId string, params *GetJobLogsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "jobId", runtime.ParamLocationPath, jobId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backplane/script/%s/job/%s/logs", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	queryValues := queryURL.Query()

	if params.Version != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "version", runtime.ParamLocationQuery, *params.Version); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	if params.Follow != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "follow", runtime.ParamLocationQuery, *params.Follow); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	queryURL.RawQuery = queryValues.Encode()

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateTestScriptRunRequest calls the generic CreateTestScriptRun builder with application/json body
func NewCreateTestScriptRunRequest(server string, clusterId string, body CreateTestScriptRunJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateTestScriptRunRequestWithBody(server, clusterId, "application/json", bodyReader)
}

// NewCreateTestScriptRunRequestWithBody generates requests for CreateTestScriptRun with any type of body
func NewCreateTestScriptRunRequestWithBody(server string, clusterId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backplane/testscript/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetTestScriptRunRequest generates requests for GetTestScriptRun
func NewGetTestScriptRunRequest(server string, clusterId string, testId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "testId", runtime.ParamLocationPath, testId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backplane/testscript/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTestScriptRunLogsRequest generates requests for GetTestScriptRunLogs
func NewGetTestScriptRunLogsRequest(server string, clusterId string, testId string, params *GetTestScriptRunLogsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clusterId", runtime.ParamLocationPath, clusterId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "testId", runtime.ParamLocationPath, testId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backplane/testscript/%s/%s/logs", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	queryValues := queryURL.Query()

	if params.Version != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "version", runtime.ParamLocationQuery, *params.Version); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	if params.Follow != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "follow", runtime.ParamLocationQuery, *params.Follow); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	queryURL.RawQuery = queryValues.Encode()

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetCloudConsole request
	GetCloudConsoleWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*GetCloudConsoleResponse, error)

	// GetCloudCredentials request
	GetCloudCredentialsWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*GetCloudCredentialsResponse, error)

	// DeleteBackplaneClusterClusterId request
	DeleteBackplaneClusterClusterIdWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*DeleteBackplaneClusterClusterIdResponse, error)

	// GetBackplaneClusterClusterId request
	GetBackplaneClusterClusterIdWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*GetBackplaneClusterClusterIdResponse, error)

	// HeadBackplaneClusterClusterId request
	HeadBackplaneClusterClusterIdWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*HeadBackplaneClusterClusterIdResponse, error)

	// OptionsBackplaneClusterClusterId request
	OptionsBackplaneClusterClusterIdWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*OptionsBackplaneClusterClusterIdResponse, error)

	// PatchBackplaneClusterClusterId request
	PatchBackplaneClusterClusterIdWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*PatchBackplaneClusterClusterIdResponse, error)

	// PostBackplaneClusterClusterId request
	PostBackplaneClusterClusterIdWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*PostBackplaneClusterClusterIdResponse, error)

	// PutBackplaneClusterClusterId request
	PutBackplaneClusterClusterIdWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*PutBackplaneClusterClusterIdResponse, error)

	// TraceBackplaneClusterClusterId request
	TraceBackplaneClusterClusterIdWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*TraceBackplaneClusterClusterIdResponse, error)

	// LoginCluster request
	LoginClusterWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*LoginClusterResponse, error)

	// GetScripts request
	GetScriptsWithResponse(ctx context.Context, params *GetScriptsParams, reqEditors ...RequestEditorFn) (*GetScriptsResponse, error)

	// GetAllJobs request
	GetAllJobsWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*GetAllJobsResponse, error)

	// CreateJob request with any body
	CreateJobWithBodyWithResponse(ctx context.Context, clusterId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateJobResponse, error)

	CreateJobWithResponse(ctx context.Context, clusterId string, body CreateJobJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateJobResponse, error)

	// DeleteJob request
	DeleteJobWithResponse(ctx context.Context, clusterId string, jobId string, reqEditors ...RequestEditorFn) (*DeleteJobResponse, error)

	// GetRun request
	GetRunWithResponse(ctx context.Context, clusterId string, jobId string, reqEditors ...RequestEditorFn) (*GetRunResponse, error)

	// GetJobLogs request
	GetJobLogsWithResponse(ctx context.Context, clusterId string, jobId string, params *GetJobLogsParams, reqEditors ...RequestEditorFn) (*GetJobLogsResponse, error)

	// CreateTestScriptRun request with any body
	CreateTestScriptRunWithBodyWithResponse(ctx context.Context, clusterId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateTestScriptRunResponse, error)

	CreateTestScriptRunWithResponse(ctx context.Context, clusterId string, body CreateTestScriptRunJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateTestScriptRunResponse, error)

	// GetTestScriptRun request
	GetTestScriptRunWithResponse(ctx context.Context, clusterId string, testId string, reqEditors ...RequestEditorFn) (*GetTestScriptRunResponse, error)

	// GetTestScriptRunLogs request
	GetTestScriptRunLogsWithResponse(ctx context.Context, clusterId string, testId string, params *GetTestScriptRunLogsParams, reqEditors ...RequestEditorFn) (*GetTestScriptRunLogsResponse, error)
}

type GetCloudConsoleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CloudCredentialsResponse
}

// Status returns HTTPResponse.Status
func (r GetCloudConsoleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCloudConsoleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCloudCredentialsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CloudCredentialsResponse
}

// Status returns HTTPResponse.Status
func (r GetCloudCredentialsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCloudCredentialsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteBackplaneClusterClusterIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteBackplaneClusterClusterIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteBackplaneClusterClusterIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetBackplaneClusterClusterIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetBackplaneClusterClusterIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBackplaneClusterClusterIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HeadBackplaneClusterClusterIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r HeadBackplaneClusterClusterIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HeadBackplaneClusterClusterIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OptionsBackplaneClusterClusterIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r OptionsBackplaneClusterClusterIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OptionsBackplaneClusterClusterIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PatchBackplaneClusterClusterIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PatchBackplaneClusterClusterIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchBackplaneClusterClusterIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostBackplaneClusterClusterIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostBackplaneClusterClusterIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostBackplaneClusterClusterIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutBackplaneClusterClusterIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PutBackplaneClusterClusterIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutBackplaneClusterClusterIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TraceBackplaneClusterClusterIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r TraceBackplaneClusterClusterIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TraceBackplaneClusterClusterIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type LoginClusterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *LoginResponse
}

// Status returns HTTPResponse.Status
func (r LoginClusterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LoginClusterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetScriptsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Scripts
}

// Status returns HTTPResponse.Status
func (r GetScriptsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetScriptsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAllJobsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Job
}

// Status returns HTTPResponse.Status
func (r GetAllJobsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAllJobsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Job
}

// Status returns HTTPResponse.Status
func (r CreateJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetRunResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Job
}

// Status returns HTTPResponse.Status
func (r GetRunResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRunResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetJobLogsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Logs
}

// Status returns HTTPResponse.Status
func (r GetJobLogsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetJobLogsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateTestScriptRunResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TestJobResult
}

// Status returns HTTPResponse.Status
func (r CreateTestScriptRunResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateTestScriptRunResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTestScriptRunResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TestJobResult
}

// Status returns HTTPResponse.Status
func (r GetTestScriptRunResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTestScriptRunResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTestScriptRunLogsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Logs
}

// Status returns HTTPResponse.Status
func (r GetTestScriptRunLogsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTestScriptRunLogsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetCloudConsoleWithResponse request returning *GetCloudConsoleResponse
func (c *ClientWithResponses) GetCloudConsoleWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*GetCloudConsoleResponse, error) {
	rsp, err := c.GetCloudConsole(ctx, clusterId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCloudConsoleResponse(rsp)
}

// GetCloudCredentialsWithResponse request returning *GetCloudCredentialsResponse
func (c *ClientWithResponses) GetCloudCredentialsWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*GetCloudCredentialsResponse, error) {
	rsp, err := c.GetCloudCredentials(ctx, clusterId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCloudCredentialsResponse(rsp)
}

// DeleteBackplaneClusterClusterIdWithResponse request returning *DeleteBackplaneClusterClusterIdResponse
func (c *ClientWithResponses) DeleteBackplaneClusterClusterIdWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*DeleteBackplaneClusterClusterIdResponse, error) {
	rsp, err := c.DeleteBackplaneClusterClusterId(ctx, clusterId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteBackplaneClusterClusterIdResponse(rsp)
}

// GetBackplaneClusterClusterIdWithResponse request returning *GetBackplaneClusterClusterIdResponse
func (c *ClientWithResponses) GetBackplaneClusterClusterIdWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*GetBackplaneClusterClusterIdResponse, error) {
	rsp, err := c.GetBackplaneClusterClusterId(ctx, clusterId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBackplaneClusterClusterIdResponse(rsp)
}

// HeadBackplaneClusterClusterIdWithResponse request returning *HeadBackplaneClusterClusterIdResponse
func (c *ClientWithResponses) HeadBackplaneClusterClusterIdWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*HeadBackplaneClusterClusterIdResponse, error) {
	rsp, err := c.HeadBackplaneClusterClusterId(ctx, clusterId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHeadBackplaneClusterClusterIdResponse(rsp)
}

// OptionsBackplaneClusterClusterIdWithResponse request returning *OptionsBackplaneClusterClusterIdResponse
func (c *ClientWithResponses) OptionsBackplaneClusterClusterIdWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*OptionsBackplaneClusterClusterIdResponse, error) {
	rsp, err := c.OptionsBackplaneClusterClusterId(ctx, clusterId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOptionsBackplaneClusterClusterIdResponse(rsp)
}

// PatchBackplaneClusterClusterIdWithResponse request returning *PatchBackplaneClusterClusterIdResponse
func (c *ClientWithResponses) PatchBackplaneClusterClusterIdWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*PatchBackplaneClusterClusterIdResponse, error) {
	rsp, err := c.PatchBackplaneClusterClusterId(ctx, clusterId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchBackplaneClusterClusterIdResponse(rsp)
}

// PostBackplaneClusterClusterIdWithResponse request returning *PostBackplaneClusterClusterIdResponse
func (c *ClientWithResponses) PostBackplaneClusterClusterIdWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*PostBackplaneClusterClusterIdResponse, error) {
	rsp, err := c.PostBackplaneClusterClusterId(ctx, clusterId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostBackplaneClusterClusterIdResponse(rsp)
}

// PutBackplaneClusterClusterIdWithResponse request returning *PutBackplaneClusterClusterIdResponse
func (c *ClientWithResponses) PutBackplaneClusterClusterIdWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*PutBackplaneClusterClusterIdResponse, error) {
	rsp, err := c.PutBackplaneClusterClusterId(ctx, clusterId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutBackplaneClusterClusterIdResponse(rsp)
}

// TraceBackplaneClusterClusterIdWithResponse request returning *TraceBackplaneClusterClusterIdResponse
func (c *ClientWithResponses) TraceBackplaneClusterClusterIdWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*TraceBackplaneClusterClusterIdResponse, error) {
	rsp, err := c.TraceBackplaneClusterClusterId(ctx, clusterId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTraceBackplaneClusterClusterIdResponse(rsp)
}

// LoginClusterWithResponse request returning *LoginClusterResponse
func (c *ClientWithResponses) LoginClusterWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*LoginClusterResponse, error) {
	rsp, err := c.LoginCluster(ctx, clusterId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLoginClusterResponse(rsp)
}

// GetScriptsWithResponse request returning *GetScriptsResponse
func (c *ClientWithResponses) GetScriptsWithResponse(ctx context.Context, params *GetScriptsParams, reqEditors ...RequestEditorFn) (*GetScriptsResponse, error) {
	rsp, err := c.GetScripts(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetScriptsResponse(rsp)
}

// GetAllJobsWithResponse request returning *GetAllJobsResponse
func (c *ClientWithResponses) GetAllJobsWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*GetAllJobsResponse, error) {
	rsp, err := c.GetAllJobs(ctx, clusterId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAllJobsResponse(rsp)
}

// CreateJobWithBodyWithResponse request with arbitrary body returning *CreateJobResponse
func (c *ClientWithResponses) CreateJobWithBodyWithResponse(ctx context.Context, clusterId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateJobResponse, error) {
	rsp, err := c.CreateJobWithBody(ctx, clusterId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateJobResponse(rsp)
}

func (c *ClientWithResponses) CreateJobWithResponse(ctx context.Context, clusterId string, body CreateJobJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateJobResponse, error) {
	rsp, err := c.CreateJob(ctx, clusterId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateJobResponse(rsp)
}

// DeleteJobWithResponse request returning *DeleteJobResponse
func (c *ClientWithResponses) DeleteJobWithResponse(ctx context.Context, clusterId string, jobId string, reqEditors ...RequestEditorFn) (*DeleteJobResponse, error) {
	rsp, err := c.DeleteJob(ctx, clusterId, jobId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteJobResponse(rsp)
}

// GetRunWithResponse request returning *GetRunResponse
func (c *ClientWithResponses) GetRunWithResponse(ctx context.Context, clusterId string, jobId string, reqEditors ...RequestEditorFn) (*GetRunResponse, error) {
	rsp, err := c.GetRun(ctx, clusterId, jobId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRunResponse(rsp)
}

// GetJobLogsWithResponse request returning *GetJobLogsResponse
func (c *ClientWithResponses) GetJobLogsWithResponse(ctx context.Context, clusterId string, jobId string, params *GetJobLogsParams, reqEditors ...RequestEditorFn) (*GetJobLogsResponse, error) {
	rsp, err := c.GetJobLogs(ctx, clusterId, jobId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetJobLogsResponse(rsp)
}

// CreateTestScriptRunWithBodyWithResponse request with arbitrary body returning *CreateTestScriptRunResponse
func (c *ClientWithResponses) CreateTestScriptRunWithBodyWithResponse(ctx context.Context, clusterId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateTestScriptRunResponse, error) {
	rsp, err := c.CreateTestScriptRunWithBody(ctx, clusterId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateTestScriptRunResponse(rsp)
}

func (c *ClientWithResponses) CreateTestScriptRunWithResponse(ctx context.Context, clusterId string, body CreateTestScriptRunJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateTestScriptRunResponse, error) {
	rsp, err := c.CreateTestScriptRun(ctx, clusterId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateTestScriptRunResponse(rsp)
}

// GetTestScriptRunWithResponse request returning *GetTestScriptRunResponse
func (c *ClientWithResponses) GetTestScriptRunWithResponse(ctx context.Context, clusterId string, testId string, reqEditors ...RequestEditorFn) (*GetTestScriptRunResponse, error) {
	rsp, err := c.GetTestScriptRun(ctx, clusterId, testId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTestScriptRunResponse(rsp)
}

// GetTestScriptRunLogsWithResponse request returning *GetTestScriptRunLogsResponse
func (c *ClientWithResponses) GetTestScriptRunLogsWithResponse(ctx context.Context, clusterId string, testId string, params *GetTestScriptRunLogsParams, reqEditors ...RequestEditorFn) (*GetTestScriptRunLogsResponse, error) {
	rsp, err := c.GetTestScriptRunLogs(ctx, clusterId, testId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTestScriptRunLogsResponse(rsp)
}

// ParseGetCloudConsoleResponse parses an HTTP response from a GetCloudConsoleWithResponse call
func ParseGetCloudConsoleResponse(rsp *http.Response) (*GetCloudConsoleResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCloudConsoleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CloudCredentialsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetCloudCredentialsResponse parses an HTTP response from a GetCloudCredentialsWithResponse call
func ParseGetCloudCredentialsResponse(rsp *http.Response) (*GetCloudCredentialsResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCloudCredentialsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CloudCredentialsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteBackplaneClusterClusterIdResponse parses an HTTP response from a DeleteBackplaneClusterClusterIdWithResponse call
func ParseDeleteBackplaneClusterClusterIdResponse(rsp *http.Response) (*DeleteBackplaneClusterClusterIdResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteBackplaneClusterClusterIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetBackplaneClusterClusterIdResponse parses an HTTP response from a GetBackplaneClusterClusterIdWithResponse call
func ParseGetBackplaneClusterClusterIdResponse(rsp *http.Response) (*GetBackplaneClusterClusterIdResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBackplaneClusterClusterIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseHeadBackplaneClusterClusterIdResponse parses an HTTP response from a HeadBackplaneClusterClusterIdWithResponse call
func ParseHeadBackplaneClusterClusterIdResponse(rsp *http.Response) (*HeadBackplaneClusterClusterIdResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HeadBackplaneClusterClusterIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseOptionsBackplaneClusterClusterIdResponse parses an HTTP response from a OptionsBackplaneClusterClusterIdWithResponse call
func ParseOptionsBackplaneClusterClusterIdResponse(rsp *http.Response) (*OptionsBackplaneClusterClusterIdResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OptionsBackplaneClusterClusterIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePatchBackplaneClusterClusterIdResponse parses an HTTP response from a PatchBackplaneClusterClusterIdWithResponse call
func ParsePatchBackplaneClusterClusterIdResponse(rsp *http.Response) (*PatchBackplaneClusterClusterIdResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchBackplaneClusterClusterIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostBackplaneClusterClusterIdResponse parses an HTTP response from a PostBackplaneClusterClusterIdWithResponse call
func ParsePostBackplaneClusterClusterIdResponse(rsp *http.Response) (*PostBackplaneClusterClusterIdResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostBackplaneClusterClusterIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePutBackplaneClusterClusterIdResponse parses an HTTP response from a PutBackplaneClusterClusterIdWithResponse call
func ParsePutBackplaneClusterClusterIdResponse(rsp *http.Response) (*PutBackplaneClusterClusterIdResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutBackplaneClusterClusterIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseTraceBackplaneClusterClusterIdResponse parses an HTTP response from a TraceBackplaneClusterClusterIdWithResponse call
func ParseTraceBackplaneClusterClusterIdResponse(rsp *http.Response) (*TraceBackplaneClusterClusterIdResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TraceBackplaneClusterClusterIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseLoginClusterResponse parses an HTTP response from a LoginClusterWithResponse call
func ParseLoginClusterResponse(rsp *http.Response) (*LoginClusterResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LoginClusterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LoginResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetScriptsResponse parses an HTTP response from a GetScriptsWithResponse call
func ParseGetScriptsResponse(rsp *http.Response) (*GetScriptsResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetScriptsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Scripts
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetAllJobsResponse parses an HTTP response from a GetAllJobsWithResponse call
func ParseGetAllJobsResponse(rsp *http.Response) (*GetAllJobsResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAllJobsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Job
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateJobResponse parses an HTTP response from a CreateJobWithResponse call
func ParseCreateJobResponse(rsp *http.Response) (*CreateJobResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Job
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteJobResponse parses an HTTP response from a DeleteJobWithResponse call
func ParseDeleteJobResponse(rsp *http.Response) (*DeleteJobResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetRunResponse parses an HTTP response from a GetRunWithResponse call
func ParseGetRunResponse(rsp *http.Response) (*GetRunResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRunResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Job
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetJobLogsResponse parses an HTTP response from a GetJobLogsWithResponse call
func ParseGetJobLogsResponse(rsp *http.Response) (*GetJobLogsResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetJobLogsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Logs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 200:
		// Content-type (application/octet-stream) unsupported

	}

	return response, nil
}

// ParseCreateTestScriptRunResponse parses an HTTP response from a CreateTestScriptRunWithResponse call
func ParseCreateTestScriptRunResponse(rsp *http.Response) (*CreateTestScriptRunResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateTestScriptRunResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TestJobResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetTestScriptRunResponse parses an HTTP response from a GetTestScriptRunWithResponse call
func ParseGetTestScriptRunResponse(rsp *http.Response) (*GetTestScriptRunResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTestScriptRunResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TestJobResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetTestScriptRunLogsResponse parses an HTTP response from a GetTestScriptRunLogsWithResponse call
func ParseGetTestScriptRunLogsResponse(rsp *http.Response) (*GetTestScriptRunLogsResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTestScriptRunLogsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Logs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 200:
		// Content-type (application/octet-stream) unsupported

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+wc2XIbN/JXULP7sJsako6PVEpvshQlUnywKHmTrdi1hZlpciCBwBgHJa6L/76FYy4O",
	"hqQU0etIeuPg6Ab6QnejwS9RyucFZ8CUjA6+RDLNYY7tzyPKdXYkIAOmCKZyArLgTILpy0CmghSKcBYd",
	"RGUPmnKBUjMN5ZhlFEQUR4XgBQhFwAJNqZYKxOlxF8pR1RVHallAdBBJJQibRas4SjmTnMIbwq66M00r",
	"UhypHJAfGCNuezENQqt3FVqH2UBjyGZYAmZ2Xpcopn3TXDv5syYCsujgjwZp4kgqrLQ84hlEn6p5PLmE",
	"VBmcRwKwgjOeGLRrBMaMM5Ji+g7PA6wyrYhPLalcuyGc0Cy0tQILPAcFwkLGWUbcVsYtjJ1pbYyHaI4L",
	"g7KGZuWkXkGM5loqlADCaEqxQm6jCLMMzbFKc5AfmRnegJBBSrGADHFmIc1B4Qwr/LGxkZJeq14KXoBU",
	"nortRb/m2dJJsxlH2AxhpEAqdMmTjkxnYjnRAQk4oXhmqEtYRlKsAF3noHIQpm0GDIRpM3DnBTU/uUBw",
	"A6lW0CBOvZ2EcwqYPSDGxJHDY6gd4AGW8MNLBCzlGWSltCaGM/0i60a99UgN0L8LmEYH0d9GtaEbeSs3",
	"Om+PXtfIxuo6kENq+RNbHENKu0rZ2tiXDh8a36VuAlugBRahLV5BgFi/wrIxNTStskOdub+VYpkTWSJG",
	"RAYsVyWCq/DuJ4ApkYZ46xS446IXmOqAFbswMid4ClJChuygrYQLLlkILrqLnYOUeBbAa8ejt747JH61",
	"3e5M/uXiYozcAGREup5PmIIZiPAag1b+kienWUCUGNKMfNaASGYtjz3CpkvH2kue9KnNJU/O7cq2acxZ",
	"NXAV99PpEOVAi6mmyA8pT2ctISjTpv3t8asupLfHr0rOmjHoOufOJkNmG5093oHVZ80dtokJLEDKn1g2",
	"OiGMyBwpsn5mRnE05WKOVXQQZVjBwAyJ4ohpSnFCITpQQkNgn8AWMkQuLAS2ugBsQQRnc2Cq3y5HcUQU",
	"zLcyq6mRNU0sLvPN8BxkgdMeN8F2rfkKCZizUOANtnc3m+uVRagu7nPTfAui9yhhF7DXvXWgwPTcWPsx",
	"sMxAiKOJZsz9OtdpCpBBFsXRCSbU/vjArhi/NiT4lVDT9GknCXyDE6B3Oh8SQWAaOiWoAXmXM6J3orWl",
	"Adr9y7ZXcrg234tUcNd8Rlh/6GC7S6soymHxrgZ53m+KC8Fvlv/RggQIoRM4HJ8iOwR9mJze1pRvseJu",
	"2wFLQ31rhwaVVBY8282ejTkl6XKiKXTR4IL8LLgu7EdlKTo7bDEvjm4GHBdkYDY1AzaAGyXwQGG34iWe",
	"UzO2hBzzuQFcKMd2xg2PuRYpfJi8uX+8a/DXsAvfZa3WveNuQe/BvD+s6xgXIJL7x2ahtjCFZG7y+vAo",
	"EOi+Pjzybj+2TT0x/4RTMPLaXv2mo6Ih43fb1jrmde7x26zGQklwak34HZnK1xex2nFigtO1xbeW0zEB",
	"rbO9m7O4LzYExeS88gPWzBKl/Bqy2jSthyEkzdHM9iIsAPnxPtpzPmzXAdos/qs4wlrlzstfO1dte9sd",
	"iNGMqFwn1tk0NAxmjzanWE40pUv0WWNKpgQyxDoplxgRFxw7f8Z0Gsk4zUau38wYfmRvffDtXPoYvZ0g",
	"wgYFNW5ZmkNqc17AplykYKnzMeiW3dW58C6fCfavc6wQUSjjIKPd3VoW9msXWBDjJf8Jtzaog6s4sn7J",
	"lqW4Mf24g2DZTAcdkIuaUNWg2qUsliq3BjHBMg+4iXFUYJV3oY6xytFU8LldoYCCI8G5KqOo9cxQAxyI",
	"OabBJOm47GpDQVNCAXFmBD+Y3kxwutUymnPBuEw5F+p4s7jZMSBaAmdZ4STCSBslUsndvKDzTrpnLZZw",
	"eyyTUJ2jqWOS7mJWtmlcr7r8WWk3rAsiqNVgJxR1ZLJF9neXa+ZN473L0+YcuqWIx97mQwBaxUO/Ks+Y",
	"xpbjNQGpKPupkr3dqVwHvusk9mnoCUhNVU8y2pwRzWuWOh/tczq9EdPO8bFZhj1p/YDajm0JiMvIOSQI",
	"ZpXBVFUjU2X13yD3JimYpFrjtIf7KZTtl5BqQdTy3FDe0eM1YAHCHPnmK7FfJ2U24fJaRevZ8bPfLpDi",
	"V8CQERKb/zXAogM/uV5grlThPDnCpjyw0/EpOuECJTi9Kihm1qcgyqhu9LpsGxyOTRS6ACHdrO+Hz4bP",
	"XN4WGC5IdBC9GD4bvojcmWE3NapAjuyt28hffo2+lHdJ2cqMm4GVKiMf1kM3/Ih+BuVu+NycqH2r8Efo",
	"oPNQkYl0BcMUffhgb6uIGWBPslLxq8ssIx4121xWzClESJk/2YjKCrnd4PNnz2wAwZkCplxoW1CS2l2M",
	"LqUzCTW8TerXe51pWdfe7PsrQ/mXHezfjb7bHaFLLgegv8YZmsBnDVI5NC/2guaEi4RkGTCH5OVekPhL",
	"W8S4QlOuWeaQ/bAXZO+4QjhNobDOgsH0ak8sOi0l/BzEAgQqB8aR1PM5FkunQP6y26sd0oJ62+zF387o",
	"amkthLfT1Mat9ZO2Pmnrk7Zu1laDcD/M+sVVt6CMSLO3rN8y1BK8zTLY5qY9GDlXgoKCrk04tu2V++AZ",
	"e9TS44Zqfv/7713HxDSu4uh5qO+563sR6nvh+l6G+l66vlehPtPYJtTYJuCvdAKpoiOeIlwQJJyy2bIb",
	"bD1EVvtOA+MKreJeQ/l4KZIDzrok+QVw9nhp4ioYZJcs713H46XMN+E9FFileZc5Y9P8iFnDZcC2jbl8",
	"xMat0CGS6EdMESX85U6bJhem+bFSpe1SUT4jrONQfRuGL6jithbC8yraY2zVLskIuLe+KEOnKUg51TRG",
	"ApQWTPqKCS1IeYPlOlCdkd9XGFb59PsKwBpBw1530JJ0R2nF+wODuqiqz+Ut89CdQ91K7GcNYlmLbH3B",
	"GP2/QvtyvQESnVci9xTR74bEX3CZWPukDOj3JcAfmAl2XfW6QniBiS129Fl7GQiCKZH2drsS53JsXdCZ",
	"Y2mzBFIixcPC37Lhl64ctk8ZDik944n8s+ZzpwudM54ECiI6ZDvjSXmj8sCEev+C5kp9q0rfroRhSss7",
	"MFmeSVXtS6+Uxd+yG1A/7nHgQFYPJO4ntVrBX7Uv1cyKV3s0/BXKPqNPl8jWBEOGsOP3k77co744xjvS",
	"Du2RoThK7JO5qZaQoWuicnT1o38p4AsQd7PJoy/2ScJqe87SCfZW/fO3w2Ylp8edmu2AFronEbfRwPhb",
	"ujV5utK4GxJzurauM/avZE6+ayUzOJ9/VZxxJaYQCCrOFS+clttqjn9YURa6UP+MbX2VgDlf2PLKSskl",
	"EkDdoxpePRbalGefuJqTHbXYPWsknD0OXd7naTnRrCyTeZhO5Z4jpVoUv7LVsIF4VXUa9maNytYLLPl7",
	"m/N3VD4x6VPcM57Ytynf8BHsi6Bs3bdNLw3RMUyxpgoRic7O37+L0eK5+S2VADx3lWmhbEdZTnWrJZwX",
	"kJLpEhH/VIrPJJI51zQzztKUu4rAYQ9K1x/C2Hg8++CMlRUpI6hNEDxVoAaOR7cG1dGkMc8cL7wgPsD4",
	"4AH5SFNQaV7pTyg15FmJm0Wfa6ZOgVRdc2ez+Bsi5wuQPie6o5PydTRvX4F8+R8WXzmYb9csh2qN7D9n",
	"+Ock7eLextWCE/vv9yWNtr6b/Beyv7wOH45PrQ5XadevfVVRFVm9f/fm38gsxyeClS8blzHijC4biWFi",
	"nCw2KATPdGplofEMSO6m7aMvrtJ7Y3nkrVXeuzYOdPVnLBlKlv4VrtmSU9lGWoXBdbXbsH3wVemPO3LZ",
	"ahqqhwbCDpFPRuAvbQTKpOPXsQNbI5yWMbhlrPPNGoSnmOgpJtpgSJ2T/WRFH4orZRl6ezvaePtm7Vzz",
	"1dsfn4y0S1sh76ygFtQ/X5MHo1GrlmpYCLLACoY5WcDQ69aQF8BkTqZqmPJ5ZMDdDBIsYWCz0HK/ZTk3",
	"A7+MAckG1p6HX2Pv3WaYpVz9KAe2FsoMeNiFhjcDB3lAMZsFHv+u/hcAAP//DY74H0NUAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
